spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_querydsl
    username: root
    password: 123456
  jpa:
    properties:
      show_sql: true
      format_sql: true
    open-in-view: false # disable this anti pattern
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: create
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    serialization:
      FAIL_ON_EMPTY_BEANS: false
